# Generated by Django 4.2.9 on 2024-02-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appcomment_appsavetext_alter_appuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppComment',
        ),
    ]
