# Generated by Django 4.2.11 on 2024-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appuser_email_alter_appuser_password_appsave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='userSymbol',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
